// Auto-generowane z wiedza.json — warstwa danych aplikacji (offline, file://)
window.WIEDZA = {
  "meta": {
    "tytul": "Refleksologia — baza wiedzy",
    "zrodlo": "Refleksologia (metoda Ingham, oprac. Wanda Budzanowska-Bratko, 1996)",
    "instytut": "Polski Instytut Refleksologii (zał. 1995), www.refleksologia.com, awbratko@gmail.com",
    "wersja": "1.0",
    "uwaga": "Materiał edukacyjny. Refleksologia nie diagnozuje i nie przepisuje leków — jest dodatkiem wspierającym homeostazę, nie medycyną."
  },
  "bezpieczenstwo": [
    "Nie jesteśmy lekarzami i nie zastępujemy lekarzy.",
    "Refleksologia jest DODATKIEM do problemów zdrowia — nie praktykujemy medycyny.",
    "Refleksologia pomaga ciału uzyskać homeostazę (naturalną równowagę).",
    "Refleksolog nie diagnozuje ani nie przepisuje leków, w żadnym wypadku i pod żadnym pozorem (D.C.B.).",
    "Nie wolno sugerować ani weryfikować leków już przepisanych przez lekarza.",
    "Nie prowadzić terapii ukierunkowanej na konkretne schorzenie — pracujemy z całym ciałem dla równowagi.",
    "NIGDY nie sugerować zmniejszenia dawki insuliny bez uprzedniego skontaktowania się z lekarzem rodzinnym.",
    "Na pytanie pacjenta o bolący refleks określać najwyżej rejon ciała (głowa / klatka piersiowa / jama brzuszna / miednica), nie konkretny narząd.",
    "Nigdy nie łączyć pracy refleksologa ze sprzedażą jakichkolwiek artykułów.",
    "Gdy pacjent ma problem nieprzedyskutowany z lekarzem — zasugerować wizytę u lekarza.",
    "Przedawkowanie zabiegu daje nieszkodliwe efekty oczyszczania (zmęczenie, katar, częstsze wydalanie) — zmniejszyć intensywność.",
    "Mapy graficzne objęte są prawem autorskim: © POLISH COPYRIGHT — WANDA BRATKO 1996 — nie kopiować ani nie publikować."
  ],
  "rozdzialy": [
    {
      "id": "r1", "nr": 1, "tytul": "Historia refleksologii", "strony": "23-27",
      "streszczenie": "Korzenie w starożytnym Egipcie. Współczesna refleksologia wywodzi się z terapii strefowej dr. Williama Fitzgeralda, rozwiniętej przez dr. Joe Shelby Rileya i przede wszystkim Eunice Ingham — twórczynię refleksologii stóp i map stref.",
      "fakty": [
        "Pochodzenie refleksologii wiąże się ze starożytnym Egiptem (inskrypcja w grobowcu lekarskim — mastaba).",
        "Dr William H. Fitzgerald jest twórcą terapii strefowej (zone therapy).",
        "Fitzgerald w 1917 r. opublikował książkę „Terapia strefowa albo uśmierzanie bólu w domu”.",
        "Eunice Ingham rozwinęła refleksologię stóp na początku lat 30. XX wieku.",
        "Eunice Ingham pracowała na stopach głównie kciukiem i palcami, bez przyrządów.",
        "W 1938 r. Eunice Ingham wydała książkę „Historie, które stopy mogą opowiedzieć” (Stories the Feet Can Tell).",
        "Eunice Ingham zmarła w grudniu 1974 r. w wieku 85 lat.",
        "Metoda Ingham jest przewodnią metodą refleksologii na świecie.",
        "Kontynuację nauczania zapewniają Narodowy i Międzynarodowy Instytut Refleksologii."
      ]
    },
    {
      "id": "r2", "nr": 2, "tytul": "Co to jest refleksologia? Teoria stref", "strony": "31-50",
      "streszczenie": "Refleksologia to nauka o refleksach w stopach i dłoniach połączonych ze wszystkimi gruczołami, organami i częściami ciała. Podstawa teoretyczna: teoria 10 podłużnych stref biegnących od palców do głowy. Cel: homeostaza.",
      "fakty": [
        "Refleksologia to nauka o refleksach w stopach i dłoniach połączonych z organami, gruczołami i częściami ciała.",
        "Miejsca odpowiadające: dłoń ↔ podeszwa stopy, łokieć ↔ kolano, kostka ↔ przegub (nadgarstek), przedramię ↔ podudzie.",
        "Gdy nie można pracować na bolącym miejscu (np. złamana noga), oddziałuje się na odpowiadające miejsce na ręce.",
        "Refleksologia skupia się na stopach, bo są najbardziej uczulone na dotyk i najlepiej zabezpieczone.",
        "Rejony pomocnicze potęgują działanie przesyłane do rejonu dolegliwości.",
        "Homeostaza to stan równowagi (balansu) pracy organizmu.",
        "Ciało dzieli się na 10 podłużnych stref biegnących od palców do głowy.",
        "Każda z 10 stref odpowiada jednemu palcowi dłoni lub stopy.",
        "Organ w danej strefie ma swój refleks w tej samej strefie stopy.",
        "Prawa stopa odpowiada prawej połowie ciała, lewa stopa — lewej połowie ciała.",
        "Duży palec stopy zawiera 5 głównych stref i jest głównym punktem orientacyjnym dla głowy.",
        "Część stopy od dużego palca nazywamy wewnętrzną (środkową), od małego palca — zewnętrzną (boczną).",
        "Cztery główne linie pomocnicze to: linia przepony (splotu słonecznego), linia pasa (talii), linia pięty, ścięgno.",
        "Refleksy kręgosłupa znajdują się na wewnętrznej krawędzi stopy (strefa pierwsza).",
        "Wg książki ok. 75% zachorowań jest spowodowanych stresami i napięciami nerwowymi.",
        "Refleksologia nigdy nie prowadzi do przedawkowania i nie może uszkodzić organizmu.",
        "Refleksy biegną przez strefy, ale nie są nerwami.",
        "Splot słoneczny znajduje się poniżej mostka i działa jak „tablica rozdzielcza nerwów”."
      ]
    },
    {
      "id": "r3", "nr": 3, "tytul": "Definicje podstawowych określeń", "strony": "45-50",
      "streszczenie": "Słownik punktów orientacyjnych stopy, linii pomocniczych i technik pracy — fundament terminologiczny.",
      "fakty": [
        "Podstawa palców stopy to miejsce połączenia palców ze stopą („korzenie” palców).",
        "Przepona to warstwa mięśniowa — „podłoga” klatki piersiowej i „dach” jamy brzusznej.",
        "Splot słoneczny nazywamy „mózgiem jamy brzusznej”; leży na linii przepony między pierwszym a drugim palcem.",
        "Linia pasa wyznaczana jest od piątej kości śródstopia w poprzek stopy.",
        "Linia pięty znajduje się na zakończeniu miękkiego podbicia, gdzie stopa przechodzi w piętę.",
        "Refleksy kręgów karku są u podstawy dużego palca na wewnętrznej krawędzi stopy.",
        "Technika nacisku i wycofania służy punktom wymagającym dokładnego ucisku (przysadka, zastawka krętniczo-kątnicza, esica).",
        "Chodzenie „na krzyż” to praca ze zmianą kierunków i rąk dla pełnego pokrycia rejonu.",
        "„Kryształki” to wyczuwalne ziarenka odłożone w niektórych partiach stóp (np. kark, ramiona).",
        "Technika uciskowo-przesuwowa kciuka i chodzenie po krawędzi stosowane są przy refleksach oczu i uszu.",
        "Rotacja to okrężne oddziaływanie z podtrzymaniem drugą ręką, na przemian w obu kierunkach.",
        "Wcięcie kości sześciennej to miękkie wgłębienie po zewnętrznej stronie stopy poniżej linii talii."
      ]
    },
    {
      "id": "r4", "nr": 4, "tytul": "Techniki pracy", "strony": "53-65",
      "streszczenie": "Podstawowe techniki: kciuk, palec, uciskowo-wycofująca, rotacja oraz techniki relaksacyjne. Zasada: kciuk i palec chodzą zawsze tylko do przodu, zginając się w pierwszym stawie pod kątem ~45°.",
      "fakty": [
        "Kciuk i palec „chodzą” zawsze tylko do przodu, nigdy do tyłu ani na bok.",
        "Kciuk pracuje zewnętrznym narożnikiem (krawędzią), zgięty w pierwszym stawie, pod kątem ok. 45°.",
        "Odchylamy tylko pierwszy staw i nie za wysoko — by unikać przeciążeń pracującego, nie uciskać paznokciem pacjenta, nie pomijać miejsc do pobudzenia.",
        "Palec wskazujący (węższy od kciuka) stosujemy tam, gdzie praca kciukiem jest mniej efektywna; pozostałe palce służą za dźwignię.",
        "Technika uciskowo-wycofująca („metoda trzmiela” / „główki szpilki”) służy małym, głębszym refleksom — nacisk i wycofanie w poprzek, bez wychodzenia poza punkt.",
        "Technika rotacji refleksu jest dla miejsc delikatnych i bolących — ucisk szpilkowy + poruszanie stopy w kierunku kciuka.",
        "Delikatny refleks bywa „chodzony” w kilku kierunkach (góra, dół, w poprzek).",
        "Główne techniki relaksacyjne: do tyłu i do przodu, ugniatanie śródstopia, skręt kręgosłupa, rozluźnianie kostki, obracanie kostki, rotacja dużego palca, przepona — głębokie oddychanie i zwalnianie napięcia.",
        "Technikę przepony (głębokie oddychanie) stosuje się przeważnie na zakończenie zabiegu; ucisk zwalniamy o ok. 50% przy wydechu, powtarzamy 4-5 razy.",
        "Refleks zwalniania napięcia przepony jest szczególnie skuteczny u osób pobudliwych i z wysokim ciśnieniem."
      ]
    },
    {
      "id": "r5", "nr": 5, "tytul": "Układ kostny, nerwowy i mięśniowy", "strony": "69-80",
      "streszczenie": "Trzy powiązane układy. Nacisk na układ kostny stopy (punkt odniesienia technik) i kręgosłup (centrum układu nerwowego). Na refleksach kręgosłupa pracujemy w każdym zabiegu.",
      "fakty": [
        "Ciało ma 206 kości; prawie ¼ z nich znajduje się w stopach.",
        "Każda stopa składa się z 26 kości, 107 wiązadeł i 19 mięśni.",
        "Kości magazynują minerały, głównie wapń; osteoblasty produkują kolagen.",
        "Stopa odpowiada budowie ręki (śródstopie ↔ śródręcze, kość stępu ↔ kość przegubu).",
        "Mózg ma dwie półkule: lewa kontroluje prawą stronę ciała, prawa — lewą.",
        "Z mózgu wychodzi 12 par nerwów czaszkowych.",
        "Kręgosłup ma 5 grup kręgów: szyjne 7, piersiowe 12, lędźwiowe 5, krzyżowa + ogonowa.",
        "Kręgi oddziela dysk pełniący rolę poduszki amortyzującej wstrząsy.",
        "Z kręgosłupa wychodzi 31 par nerwów.",
        "Na refleksach kręgosłupa pracujemy w każdym zabiegu, na całym jego przebiegu.",
        "Pracę na stopie zaczynamy prawą dłonią od prawej stopy klienta.",
        "Mięśnie dzielą się na zależne (warunkowe) i niezależne (bezwarunkowe)."
      ]
    },
    {
      "id": "r6", "nr": 6, "tytul": "Układ sercowo-naczyniowy", "strony": "103-112",
      "streszczenie": "Serce pompuje tlen i składniki życiowe do tkanek. Główny refleks serca: w poprzek śródstopia lewej stopy. Układ krwionośny nie ma jednego refleksu — pracujemy na wszystkich.",
      "fakty": [
        "Serce pompuje ~5 l krwi/min w spoczynku, ~35 l/min przy wysiłku.",
        "Serce leży ⅓ po prawej, ⅔ po lewej stronie linii środkowej; ma 2 przedsionki i 2 komory.",
        "Serce zatrzymuje dla siebie tylko ~5% pompowanej krwi (naczynia wieńcowe).",
        "Mózg potrzebuje więcej krwi i tlenu niż samo serce.",
        "Główny refleks serca: w poprzek śródstopia lewej stopy, najczulej między 1. a 2. palcem.",
        "Przy problemach z sercem pracuje się też na refleksach lewego ramienia/ręki.",
        "Miejsce pomocnicze przy niedomaganiach serca to nadnercze (adrenalina).",
        "Przy nadciśnieniu pracuje się na refleksach przepony.",
        "Nigdy nie pracujemy bezpośrednio na skrzepach — tylko w rejonach równoległych.",
        "Przy paraliżu pracujemy na czubku dużego palca po przeciwnej stronie ciała (przeciwna półkula mózgu).",
        "Każdy kilogram nadwagi to ok. 60 km dodatkowych naczyń włosowatych."
      ]
    },
    {
      "id": "r7", "nr": 7, "tytul": "Układ limfatyczny", "strony": "115-121",
      "streszczenie": "Sieć naczyń z zastawkami; oczyszcza tkanki i broni organizm (węzły chłonne, śledziona, migdały, grasica). Praca głównie na pachwinie (kostka), klatce piersiowej (wierzch stopy), migdałkach (duży palec) i grasicy.",
      "fakty": [
        "Limfa pochodzi z plazmy krwi i jest bezbarwną cieczą; jej węzły są bastionami obronnymi.",
        "Śledziona to największe skupisko tkanki limfatycznej; magazynuje żelazo, ważna przy anemii.",
        "Migdały produkują przeciwciała i działają jak filtry.",
        "Grasica jest ważnym refleksem u dzieci; produkuje antyciała, z wiekiem maleje.",
        "Miejsce odpowiadające pachwinie na stopie to połączenie stopy z nogą w kostce.",
        "Wierzch stopy reprezentuje płuca, klatkę piersiową i piersi; praca na wierzchu jest łatwiejsza i skuteczniejsza.",
        "Refleksy migdałków są wokół dużego palca na wysokości 1/3 od jego podstawy.",
        "Miejsce pomocnicze dla migdałków to małe palce stopy.",
        "Refleks grasicy leży poniżej refleksu tarczycy."
      ]
    },
    {
      "id": "r8", "nr": 8, "tytul": "Narządy zmysłu", "strony": "125-135",
      "streszczenie": "Pięć narządów zmysłu. Refleksy oczu i uszu u podstawy małych palców; smak/zapach w środkowej 1/3 dużego palca; skóra zależy od tarczycy i nadnercza.",
      "fakty": [
        "Pięć narządów zmysłu: skóra (dotyk), oczy (wzrok), uszy (słuch+równowaga), nos (powonienie), język (smak).",
        "Skóra produkuje witaminę D, reguluje temperaturę i wydala ~500 cm³ wody.",
        "Nos rozróżnia ok. 4000 zapachów.",
        "Cztery podstawowe smaki: słodki (czubek), gorzki (tył), słony (krawędzie), kwaśny.",
        "W uchu dźwięk wzmacniają 3 kosteczki: kowadełko, młoteczek, strzemiączko (~22×).",
        "Za równowagę odpowiada ucho środkowe (kanały półkoliste z płynem śródchłonkowym).",
        "Trąbka Eustachiusza wyrównuje ciśnienie i łączy ucho środkowe z gardłem.",
        "Refleksy oczu i uszu leżą u podstawy małych palców obu stóp (te same strefy).",
        "Miejsce pomocnicze dla oczu to refleksy nerek (3. strefa).",
        "Refleksy zapachu i smaku są w środkowej 1/3 dużego palca.",
        "Dla skóry kluczowe są gruczoły: tarczyca i nadnercze.",
        "Praca na refleksach oczu wzmacnia widzenie, ale nie zastępuje okularów."
      ]
    },
    {
      "id": "r9", "nr": 9, "tytul": "Układ oddechowy", "strony": "139-148",
      "streszczenie": "Wymiana CO₂ na tlen. Praca głównie między linią przepony a podstawą palców (płuca, klatka piersiowa) oraz na palcach (zatoki, nos, gardło). Mocny akcent na szkodliwość palenia.",
      "fakty": [
        "Układ oddechowy: nos, gardło, krtań, tchawica, oskrzela, płuca, przepona, zatoki.",
        "Prawe płuco ma 3 płaty, lewe płuco ma 2 płaty.",
        "Liczba pęcherzyków płucnych: 300 mln do 1 mld; powierzchnia wymiany ~56 m².",
        "Przy wdechu przepona się kurczy (zwiększa pojemność klatki), przy wydechu wraca.",
        "Dym papierosowy paraliżuje rzęski oczyszczające drogi oddechowe → rozedma płuc.",
        "Refleksy płuc: od linii przepony w górę do podstawy palców (spód i wierzch stopy).",
        "Refleksy zatok znajdują się we wszystkich palcach stopy.",
        "Refleksy nosa są na 1/3 poduszki dużego palca; gardła — u podstawy dużego palca.",
        "Refleksy zatok odpowiadają całej głowie z wyłączeniem oczu, uszu i zębów.",
        "Rejony pomocnicze zatok: zastawka krętniczo-kątnicza (tylko prawa noga), przysadka, nadnercze.",
        "Przepona to kluczowy refleks przy napięciach i stresach."
      ]
    },
    {
      "id": "r10", "nr": 10, "tytul": "Układ trawienny", "strony": "151-170",
      "streszczenie": "Przerabia pokarm na substancje przyswajalne. Praca „śladem pokarmu” od ust (duży palec) w dół po obu stopach. Kluczowa zasada: refleksologia NIE jest masażem.",
      "fakty": [
        "Droga pokarmu: jama ustna → gardło → przełyk → żołądek → jelito cienkie → jelito grube → odbytnica → odbyt.",
        "Żołądek: ~35 mln gruczołów, ~2,8 l soków/dobę, pojemność ~1,89 l; ~85% refleksów żołądka na lewej stopie.",
        "Wątroba waży ok. 1,5 kg, wykonuje ponad 500 czynności; refleksy na prawej stopie (między linią pasa a przepony).",
        "„Gdy wątroba zawiedzie — ciało umiera.”",
        "Woreczek żółciowy ma kształt gruszki; wątroba produkuje ~500 cc żółci dziennie; refleks na prawej stopie, czasem skuteczniejszy na wierzchu.",
        "Trzustka: długość 152,4 mm, waga ~85 g; refleksy na obu stopach, główne na lewej; produkuje insulinę i glikogen.",
        "Zastawka krętniczo-kątnicza (z wyrostkiem robaczkowym): zewnętrzna krawędź spodu PRAWEJ stopy, między 4. a 5. rejonem; technika zaczepno-wycofująca.",
        "Okrężnica esowata (esica) = najtrudniejsze miejsce dla refleksologa; to samo miejsce to refleks pęcherza moczowego (lewa stopa).",
        "Pracujemy „drogą przepływu” w jelicie grubym; jelita cienkie i grube są nierozdzielne.",
        "Refleks chroniczny (między ścięgnem Achillesa a kostką, ~2 cm nad kostką) jest wspólny dla prostaty, macicy, odbytnicy i nerwu kulszowego.",
        "REFLEKSOLOGIA NIE JEST MASAŻEM — pracujemy techniką kciuka ze zmiennym kątem (wyjątki: esica i zastawka krętniczo-kątnicza — technika zaczepno-wycofująca).",
        "Gruczoły ślinowe: przyuszna, podżuchwowa, podjęzykowa; enzym ptyalina rozpoczyna trawienie skrobi."
      ]
    },
    {
      "id": "r11", "nr": 11, "tytul": "Układ moczowy", "strony": "171-179",
      "streszczenie": "Magazynuje i wydala produkty odpadowe, pracuje całą dobę. Nerki, moczowody, pęcherz, cewka. Kluczowy przy kamieniach, infekcjach pęcherza i nadciśnieniu.",
      "fakty": [
        "Układ moczowy: nerki, moczowody (przewody moczowe), pęcherz, cewka moczowa.",
        "Nerki to główne filtry; filtrują ~1 l krwi/min (ponad 60 l/h); dorosły wydala ~1,5 l moczu dziennie.",
        "Refleksy układu moczowego są na obu stopach; pęcherz na wewnętrznej krawędzi przy linii pięty, nerka w centrum stopy, przewód moczowy wzdłuż wewnętrznej strony ścięgna.",
        "Na refleksach nerki pracujemy zawsze w obu kierunkach.",
        "Infekcje pęcherza częstsze u kobiet (krótsza cewka); zapalenie pęcherza łatwo przechodzi do nerek.",
        "Kamienie nerkowe najczęściej w przewodach moczowych — tam najwięcej bólu.",
        "Miejsca pomocnicze: nadnercza (stany zapalne), dół kręgosłupa, przytarczyczki (poziom wapnia → kamienie).",
        "Przy nadciśnieniu pracujemy na rejonie przepony/splotu słonecznego + nerki i wszystkie gruczoły.",
        "Nadciśnienie to „cichy zabójca” związany z chorobą nerek."
      ]
    },
    {
      "id": "r12", "nr": 12, "tytul": "Gruczoły wewnętrznego wydzielania", "strony": "181-192",
      "streszczenie": "Bezprzewodowe gruczoły wydzielające hormony („termostaty”). Przysadka = gruczoł główny. Refleksolog skupia się na przysadce, przytarczyczkach, tarczycy, nadnerczach, gruczołach rozrodczych i trzustce.",
      "fakty": [
        "Gruczoły wewnętrznego wydzielania są bezprzewodowe, wydzielają hormony do krwi/limfy; sterują ciałem jak „termostaty”.",
        "Przysadka mózgowa = gruczoł główny („dyrygent”), wielkości ziarenka grochu; refleks w środku powierzchni dużego palca.",
        "Refleks przysadki: usuwanie gorączki, pomoc przy omdleniach; ważny u dzieci.",
        "Przytarczyczki (przeważnie 4) kontrolują wapń i fosfor → kości; pomocne przy kamieniach nerkowych.",
        "Tarczyca w połowie szyi → refleks u podstawy dużego palca; zwana „trzecim jajnikiem”.",
        "Nadnercza nad nerkami; rdzeń produkuje adrenalinę; refleks w pół drogi między linią pasa a przepony, przy ścięgnie.",
        "Trzustka: główne refleksy na lewej stopie; główny powód pracy — cukrzyca (najlepsze efekty przy cukrzycy nabytej później).",
        "NIGDY nie zmieniać/odstawiać insuliny bez lekarza.",
        "Przy hipo- i hiperglikemii pracujemy na trzustce i wątrobie.",
        "Najlepsza kombinacja przy przysadce/nadnerczu: prawa ręka–prawa noga, lewa ręka–lewa noga."
      ]
    },
    {
      "id": "r13", "nr": 13, "tytul": "Układ rozrodczy", "strony": "195-202",
      "streszczenie": "Praca głównie w rejonie kostek (wewnętrzna = macica/prostata, zewnętrzna = jajniki/jądra) oraz wzdłuż ścięgna Achillesa (rejon chroniczny). Omawia ciążę i przekwitanie.",
      "fakty": [
        "Refleks macicy/prostaty: wewnętrzna strona stopy, w połowie linii kostka↔krawędź pięty.",
        "Refleks jajników/jąder: zewnętrzna strona stopy (strona małego palca), analogicznie w połowie odległości.",
        "Refleks macicy/prostaty to miejsce punktowe i bardzo wrażliwe — wiele kostek ma tam małe wgniecenie.",
        "Rejon przewodów jajowych/nasiennych = staw skokowy (połączenie stopy z nogą); technika obrotu kostki.",
        "Rejon ścięgna Achillesa (chroniczny) wspólny dla: prostaty, macicy, odbytnicy, nerwu kulszowego.",
        "Gruczoły piersiowe — praca na wierzchu stopy od podstawy palców do linii przepony; refleksy pomocnicze: przysadka i układ limfatyczny.",
        "Po usunięciu jajników funkcję estrogenu przejmują nadnercza → praca na nadnerczu, tarczycy, przysadce.",
        "Miejsca pomocnicze jajników/jąder: tarczyca, przysadka, nadnercza.",
        "Przy operacjach układu rozrodczego pracować PRZED i NATYCHMIAST po zabiegu.",
        "Hormony: na męskie embriony działają androgeny (najsilniejszy testosteron), na żeńskie estrogeny (z jajników)."
      ]
    },
    {
      "id": "r14", "nr": 14, "tytul": "Przebieg zabiegu", "strony": "203-210",
      "streszczenie": "Pełny zabieg wg metody Budzanowskiej-Bratko: jedna stopa A-Z, potem druga, na końcu powrót do pierwszej. Zasada nadrzędna: refleksologia nie diagnozuje i nie leczy konkretnych chorób.",
      "fakty": [
        "Pełny zabieg: jedna stopa A-Z, potem druga, na końcu powrót do pierwszej.",
        "Kolejność: przepona→palce, wszystkie palce, oko/ucho, przepona→pięta, pięta, kręgosłup, kostka (rejon rozrodczy).",
        "Zabieg trwa 30-40 min (pierwszy do 60 min); 2×/tydzień, potem 1×/tydzień.",
        "Zaczynać i kończyć technikami relaksu (splot słoneczny/przepona na początku).",
        "Nacisk: „boli, ale przyjemnie” — obserwować twarz pacjenta.",
        "Refleksolog NIE diagnozuje, NIE leczy chorób, NIE sprzedaje produktów, NIE zastępuje lekarza.",
        "Przy pytaniu o refleks — określać najwyżej rejon (głowa/klatka/brzuch/miednica), nie konkretny narząd.",
        "Przedawkowanie zabiegu daje nieszkodliwe efekty oczyszczania.",
        "Metoda Budzanowskiej-Bratko: pełny zabieg codziennie (inaczej niż program D.C. Byersa: jeden zabieg na dwa dni)."
      ]
    },
    {
      "id": "r15", "nr": 15, "tytul": "Refleksologia rąk", "strony": "213-216",
      "streszczenie": "Ręce = pole pracy samego pacjenta i wyjście, gdy nie można pracować na stopach. Te same strefy i linie co stopy. Refleksy trudniejsze do odnalezienia.",
      "fakty": [
        "Refleksologia rąk = pole do samodzielnej pracy pacjenta i wyjście, gdy nie można pracować na stopach.",
        "Ręce mają te same strefy i linie podziałowe co stopy; refleksy są trudniejsze do odnalezienia.",
        "Przestrzeń „V” (między kciukiem a wskazującym) zawiera refleksy karku, gardła, barku.",
        "Kciuk = odpowiednik dużego palca stopy; przegub dłoni = odpowiednik kostki.",
        "Na wierzchu dłoni pracować palcami, nie kciukiem; podparcie bardzo ważne.",
        "Łatwiej znaleźć bolące miejsca na stopach niż na rękach.",
        "Dobre efekty pracy na dłoniach: problemy karku, barków, piersi, płuc, zatok, kręgosłupa szyjnego."
      ]
    }
  ],
  "schorzenia": [
    {"nazwa": "Alkoholizm", "refleksy": "wątroba, trzustka, przepona"},
    {"nazwa": "Anemia", "refleksy": "śledziona, wątroba"},
    {"nazwa": "Angina Pectoris", "refleksy": "serce, płuca, kręgi szyjne, jelito esowate, przepona"},
    {"nazwa": "Artretyzm", "refleksy": "całe stopy, praca na refleksach dotkniętych schorzeniem"},
    {"nazwa": "Astma", "refleksy": "klatka piersiowa/płuca, nadnercza, zastawka krętniczo-kątnicza jelita, przepona"},
    {"nazwa": "Białaczka", "refleksy": "wszystkie gruczoły, układ limfatyczny, śledziona"},
    {"nazwa": "Bezpłodność", "refleksy": "układ rozrodczy, wszystkie gruczoły, cały kręgosłup, przepona"},
    {"nazwa": "Bezsenność", "refleksy": "przepona, wszystkie gruczoły"},
    {"nazwa": "Biegunka", "refleksy": "jelito grube wstępujące, jelito poprzeczne, przepona, wątroba, nadnercze"},
    {"nazwa": "Ciąża", "refleksy": "wszystkie gruczoły, cały kręgosłup, narządy rozrodcze, pęcherz, przepona"},
    {"nazwa": "Ciśnienie niskie", "refleksy": "nadnercze, przysadka mózgowa, tarczyca"},
    {"nazwa": "Cholesterol (wysoki poziom)", "refleksy": "tarczyca, wątroba"},
    {"nazwa": "Cuchnący oddech", "refleksy": "żołądek, wątroba, jelito cienkie, duży palec"},
    {"nazwa": "Cukrzyca", "refleksy": "trzustka, wątroba, wszystkie gruczoły"},
    {"nazwa": "Cysta (jajniki)", "refleksy": "jajniki, przysadka mózgowa, wszystkie gruczoły, macica, jajowody"},
    {"nazwa": "Czkawka", "refleksy": "przepona, żołądek"},
    {"nazwa": "Dzieciństwo (schorzenia)", "refleksy": "wszystkie gruczoły, przepona"},
    {"nazwa": "Dna (skaza moczanowa)", "refleksy": "nerki, refleksy miejsc dotkniętych chorobą"},
    {"nazwa": "Drżenie", "refleksy": "cały kręgosłup, przepona"},
    {"nazwa": "Dysk (pęknięcie)", "refleksy": "pracować na refleksach kręgosłupa"},
    {"nazwa": "Egzema", "refleksy": "przepona, wątroba, nerki, jelito cienkie"},
    {"nazwa": "Energia (brak żywotności)", "refleksy": "nadnercza, wszystkie gruczoły, tarczyca, przepona, cały kręgosłup"},
    {"nazwa": "Gardło", "refleksy": "układ limfatyczny, wszystkie palce, duży palec, nadnercze, kręgi szyjne"},
    {"nazwa": "Gazy (bóle)", "refleksy": "żołądek, przepona, jelito cienkie, wątroba"},
    {"nazwa": "Głowa (zawroty)", "refleksy": "refleksy uszu, kark, kręgi szyjne, duży palec"},
    {"nazwa": "Głowa (bóle ogólne)", "refleksy": "cały kręgosłup, przepona, wszystkie gruczoły, wszystkie palce"},
    {"nazwa": "Gruczoły", "refleksy": "duży palec, przysadka mózgowa"},
    {"nazwa": "Głuchota", "refleksy": "refleksy uszu, kręgi szyjne, boki karku, duży palec"},
    {"nazwa": "Guz (nowotwór)", "refleksy": "przysadka mózgowa, wszystkie gruczoły, refleks właściwy dla lokalizacji guza"},
    {"nazwa": "Hipoglikemia", "refleksy": "trzustka, wszystkie gruczoły, wątroba"},
    {"nazwa": "Hemoroidy", "refleksy": "przepona, nadnercza, odbytnica, jelito cienkie, wszystkie gruczoły, układ limfatyczny"},
    {"nazwa": "Influenza (grypa)", "refleksy": "klatka piersiowa, płuca, przepona, jelito cienkie, wszystkie gruczoły, układ limfatyczny"},
    {"nazwa": "Impotencja", "refleksy": "narządy rozrodcze, wszystkie gruczoły, cały kręgosłup, przepona"},
    {"nazwa": "Infekcja", "refleksy": "nadnercza, układ limfatyczny, miejsce dotknięte infekcją"},
    {"nazwa": "Jaskra", "refleksy": "refleksy oczu, gardła, karku, wszystkie palce, nerki, kręgi szyjne"},
    {"nazwa": "Jajniki", "refleksy": "jajniki, przysadka mózgowa, wszystkie gruczoły, macica, przewody jajowe"},
    {"nazwa": "Jęczmień (na oku)", "refleksy": "refleksy oka, kark, wszystkie palce"},
    {"nazwa": "Kolano opuchnięte", "refleksy": "nerki, nadnercza, układ limfatyczny, miejsce odpowiadające — łokieć"},
    {"nazwa": "Kaletka (zapalenie)", "refleksy": "refleksy kaletki, nadnercza, miejsce odpowiadające zaatakowanej kaletce"},
    {"nazwa": "Katarakta", "refleksy": "refleksy oczu, karku, kręgów szyjnych, wszystkie palce, przysadka mózgowa, nerki"},
    {"nazwa": "Klatka piersiowa (ból)", "refleksy": "jelito esowate, przepona, klatka piersiowa/płuca"},
    {"nazwa": "Kostnina (nagniotki, odciski)", "refleksy": "wokół i dokładnie na nich"},
    {"nazwa": "Kość ogonowa", "refleksy": "cały kręgosłup, nerki, biodra, ramiona"},
    {"nazwa": "Krtań (zapalenie)", "refleksy": "przepona, oskrzela, klatka piersiowa/płuca, zastawka krętniczo-kątnicza jelita, wszystkie palce"},
    {"nazwa": "Kamienie nerkowe", "refleksy": "przewody moczowe, nerki, pęcherz, przepona, przytarczyczki"},
    {"nazwa": "Kolana", "refleksy": "biodro/kolano, biodro/nerw kulszowy, dolna część kręgosłupa, miejsce odpowiadające — łokieć"},
    {"nazwa": "Kamienie żółciowe", "refleksy": "wątroba, woreczek żółciowy, tarczyca"},
    {"nazwa": "Kark (napięcia)", "refleksy": "kark, kręgi szyjne, ramiona"},
    {"nazwa": "Kręgosłup (skrzywienie)", "refleksy": "czubek i podłoże stopy między dużym i drugim palcem, cały kręgosłup, 7. kręg szyjny"},
    {"nazwa": "Kręgosłup", "refleksy": "wszystkie gruczoły, przepona, nerki, wątroba"},
    {"nazwa": "Lekomania, narkomania", "refleksy": "wszystkie gruczoły, przepona, nerki, jelito cienkie, tarczyca, nadnercze, wątroba"},
    {"nazwa": "Łuszczyca", "refleksy": "tarczyca, nadnercze, wątroba, przepona, wszystkie gruczoły"},
    {"nazwa": "Macica (wycięcie)", "refleksy": "nadnercze, tarczyca, przysadka mózgowa, macica, jajniki, przewody jajowe, przepona, okolice całej macicy"},
    {"nazwa": "Marskość wątroby", "refleksy": "wątroba, trzustka, wszystkie gruczoły"},
    {"nazwa": "Miażdżyca", "refleksy": "tarczyca, wszystkie gruczoły, węzły chłonne, praca na całych stopach"},
    {"nazwa": "Moczenie nocne", "refleksy": "nerki, przepona, moczowody, nadnercza, dolne kręgi kręgosłupa"},
    {"nazwa": "Mózg (zapalenie)", "refleksy": "duży palec, wszystkie palce, wszystkie gruczoły"},
    {"nazwa": "Migrena", "refleksy": "cały kręgosłup, przepona, przysadka mózgowa, duży palec, jelita"},
    {"nazwa": "Migdały (zapalenie)", "refleksy": "duży palec, układ limfatyczny, wszystkie palce, nadnercza, kręgi szyjne"},
    {"nazwa": "Niekontrolowane oddawanie moczu", "refleksy": "przewody moczowe, pęcherz, nerki, nadnercza, dolne kręgi kręgosłupa"},
    {"nazwa": "Nadciśnienie", "refleksy": "przepona, nerki, przysadka mózgowa, nadnercza, tarczyca"},
    {"nazwa": "Nadmierna pobudliwość", "refleksy": "przepona, wszystkie gruczoły"},
    {"nazwa": "Nudności, wymioty", "refleksy": "wątroba, woreczek żółciowy, żołądek, przepona"},
    {"nazwa": "Nerwowość", "refleksy": "przepona, wszystkie gruczoły, cały kręgosłup"},
    {"nazwa": "Niestrawność", "refleksy": "wątroba, woreczek żółciowy, żołądek, jelito cienkie, przepona"},
    {"nazwa": "Nerki (zapalenie)", "refleksy": "nerki, nadnercza"},
    {"nazwa": "Nerw (zapalenie)", "refleksy": "kręgosłup, przepona, gruczoły korespondujące z refleksami nerwów"},
    {"nazwa": "Napięcie nerwów", "refleksy": "przepona, wszystkie gruczoły, cały kręgosłup"},
    {"nazwa": "Nerw twarzowy (porażenie)", "refleksy": "kręgi szyjne, przepona"},
    {"nazwa": "Obrzęki", "refleksy": "układ limfatyczny, nerki, nadnercza"},
    {"nazwa": "Oczy (kondycja)", "refleksy": "jelito grube, wątroba, nadnercza, dolna część kręgosłupa, przepona, woreczek żółciowy"},
    {"nazwa": "Okrężnica (zapalenie)", "refleksy": "refleksy oczu, gardła/karku, wszystkie palce, nerki, górne kręgi kręgosłupa"},
    {"nazwa": "Omdlenie", "refleksy": "przysadka mózgowa"},
    {"nazwa": "Opony mózgowe (zapalenie)", "refleksy": "duży palec, cały kręgosłup, wszystkie gruczoły"},
    {"nazwa": "Opuchnięte nogi", "refleksy": "układ limfatyczny, nerki, nadnercza"},
    {"nazwa": "Opłucna (zapalenie)", "refleksy": "układ limfatyczny, nadnercza, przepona, klatka piersiowa/płuca"},
    {"nazwa": "Ostrogi na pięcie", "refleksy": "pracuj wokół ostrogi i przez chwilę na samej ostrodze"},
    {"nazwa": "Oskrzela (zapalenie)", "refleksy": "klatka piersiowa/płuca, zastawka krętniczo-kątnicza jelita, przepona i nadnercza"},
    {"nazwa": "Padaczka", "refleksy": "przepona, okrężnica, krężnica, cały kręgosłup"},
    {"nazwa": "Piersi (guzy)", "refleksy": "klatka piersiowa/płuca, układ limfatyczny, przysadka mózgowa"},
    {"nazwa": "Pęcherz (problemy)", "refleksy": "pęcherz, przewody moczowe, nerki, nadnercza, dolne kręgi kręgosłupa"},
    {"nazwa": "Pęcherz (zapalenie)", "refleksy": "pęcherz, przewody moczowe, nerki, nadnercza, dolne kręgi kręgosłupa"},
    {"nazwa": "Przeziębienie", "refleksy": "klatka piersiowa/płuca, nadnercza, jelito cienkie, układ limfatyczny, przysadka mózgowa, wszystkie palce"},
    {"nazwa": "Przepuklina", "refleksy": "okolice pachwiny, okrężnica, nadnercza"},
    {"nazwa": "Przepuklina rozwarta (rozwór przełykowy)", "refleksy": "przepona, żołądek, nadnercza"},
    {"nazwa": "Półpasiec", "refleksy": "przepona, wszystkie gruczoły, cały kręgosłup"},
    {"nazwa": "Przekwitanie (gorące uderzenia)", "refleksy": "przepona, narządy rozrodcze, wszystkie gruczoły, koniecznie macica"},
    {"nazwa": "Poranna choroba (nudności ciążowe)", "refleksy": "wszystkie gruczoły, przepona, żołądek"},
    {"nazwa": "Paraliż (porażenie)", "refleksy": "cały kręgosłup, mózg, refleksy odpowiadające"},
    {"nazwa": "Parkinson", "refleksy": "cały kręgosłup, wszystkie gruczoły, przepona, klatka piersiowa/płuca"},
    {"nazwa": "Pocące ręce i stopy", "refleksy": "wszystkie gruczoły, wątroba, jelito cienkie, nerki, przepona"},
    {"nazwa": "Prostata", "refleksy": "pęcherz, dół kręgosłupa, gruczoły narządów rozrodczych, okolice chronicznej prostaty, nadnercza, przysadka mózgowa"},
    {"nazwa": "Płuca (zapalenie)", "refleksy": "przepona, jelito cienkie, klatka piersiowa/płuca, układ limfatyczny, wszystkie gruczoły"},
    {"nazwa": "Płuca (rozedma)", "refleksy": "krężnica, nadnercza, klatka piersiowa/płuca, układ limfatyczny, przepona"},
    {"nazwa": "Porażenie (udar)", "refleksy": "czubek dużego palca strony przeciwnej do paraliżu, pozostałe palce, refleksy porażenia"},
    {"nazwa": "Przegub ręki (uszkodzony)", "refleksy": "miejsce odpowiadające — kostka, staw skokowy"},
    {"nazwa": "Ramiona", "refleksy": "refleksy ramion, kręgi szyjne, biodro, kark"},
    {"nazwa": "Ręce (dłonie)", "refleksy": "kręgi szyjne, wyższe kręgi piersiowe, ramię, biodro"},
    {"nazwa": "Ropotok", "refleksy": "duży palec, wszystkie gruczoły"},
    {"nazwa": "Rwa kulszowa", "refleksy": "biodro, nerw kulszowy, biodro-kolano, dolna część kręgosłupa, ramię, miejsce chroniczne nerwu kulszowego"},
    {"nazwa": "Schorzenie Brighta (nerki)", "refleksy": "nerki"},
    {"nazwa": "Skurcze", "refleksy": "biodro-kolano, biodro-nerw kulszowy, przytarczyczki, nadnercza, dół kręgosłupa"},
    {"nazwa": "Skurcze (miesiączkowe)", "refleksy": "macica, jajniki, przewody jajowe, przepona, dół kręgosłupa, wszystkie gruczoły"},
    {"nazwa": "Serce i kondycja", "refleksy": "klatka piersiowa/płuca, przepona, kręgi szyjne, jelito esowate, kręgi piersiowe"},
    {"nazwa": "Staw biodrowy", "refleksy": "staw biodrowy, nerw kulszowy, biodro-kolano, dolna część kręgosłupa, ramię"},
    {"nazwa": "Stwardnienie tętnic", "refleksy": "wszystkie gruczoły, węzły chłonne, praca na całych stopach"},
    {"nazwa": "MS (stwardnienie rozsiane)", "refleksy": "cały kręgosłup, wszystkie gruczoły, przepona"},
    {"nazwa": "Schorzenia podróżne (morze, lot, auto)", "refleksy": "refleksy uszu, przepona, kark, kręgosłup"},
    {"nazwa": "Smak", "refleksy": "wszystkie palce, środek 1/3 dużego palca"},
    {"nazwa": "Spojówka (zapalenie)", "refleksy": "refleksy oczu, wszystkie palce, kark, nerki"},
    {"nazwa": "Szum w uszach", "refleksy": "refleksy oczu, kręgi szyjne, kark, małe paluszki"},
    {"nazwa": "Sucha wysuszona skóra", "refleksy": "tarczyca, nadnercza"},
    {"nazwa": "Stopy (zimne i pocące)", "refleksy": "wątroba, jelito cienkie, nerki, wszystkie gruczoły"},
    {"nazwa": "Skrzepy miesiączkowe", "refleksy": "macica, jajniki, przewody jajowe, dolna część kręgosłupa, wszystkie gruczoły, przepona"},
    {"nazwa": "Tarczyca", "refleksy": "przysadka mózgowa, nadnercza, tarczyca"},
    {"nazwa": "Tik twarzowy", "refleksy": "kark, kręgi szyjne, przepona"},
    {"nazwa": "Trądzik", "refleksy": "wątroba, nadnercza, wszystkie gruczoły, nerki, jelita, tarczyca, przepona"},
    {"nazwa": "Temperatura", "refleksy": "przysadka mózgowa"},
    {"nazwa": "Wysoka temperatura", "refleksy": "krężnica, wszystkie palce, wszystkie gruczoły, okrężnica, klatka piersiowa/płuca"},
    {"nazwa": "Toczeń (lupus)", "refleksy": "wszystkie gruczoły, jelito cienkie, wątroba, cały kręgosłup"},
    {"nazwa": "Uchyłek (zapalenie)", "refleksy": "jelito grube, okrężnica, przepona, nadnercze, dół kręgosłupa, wątroba, woreczek żółciowy"},
    {"nazwa": "Uszy", "refleksy": "refleksy uszu, wszystkie palce, gardło/kark, kanały słuchowe"},
    {"nazwa": "Uderzenie krwi do głowy", "refleksy": "przepona, wszystkie gruczoły, narządy rozrodcze, okolice macicy"},
    {"nazwa": "Wyczerpanie ogólne (zmęczenie)", "refleksy": "nadnercza, przepona, wszystkie gruczoły, cały kręgosłup"},
    {"nazwa": "Wzdęcia (z oddawaniem wiatrów)", "refleksy": "jelito cienkie, żołądek, wątroba, woreczek żółciowy, trzustka"},
    {"nazwa": "Wzrost (nienormalny)", "refleksy": "przysadka mózgowa, refleksy dotknięte chorobą na stopach"},
    {"nazwa": "Wątroba (problemy)", "refleksy": "wątroba, woreczek żółciowy, cały kręgosłup"},
    {"nazwa": "Węch (zapach)", "refleksy": "duży palec, wszystkie palce"},
    {"nazwa": "Wrzody (owrzodzenia)", "refleksy": "przepona, żołądek, dwunastnica, relaks właściwy do lokalizacji wrzodów"},
    {"nazwa": "Wyrostek robaczkowy (zapalenie)", "refleksy": "zastawka krętniczo-kątnicza jelita, przepona"},
    {"nazwa": "Zaparcia", "refleksy": "wątroba, woreczek żółciowy, dół kręgosłupa, nadnercza, przepona, zastawka krętniczo-kątnicza jelita, jelito esowate"},
    {"nazwa": "Zawroty głowy", "refleksy": "boki karku, refleksy oczu, kręgi szyjne"},
    {"nazwa": "Zatrzymanie płynów (obrzęki)", "refleksy": "nerki, nadnercza, układ limfatyczny"},
    {"nazwa": "Złamania", "refleksy": "refleksy części złamanej + równolegle refleksy korespondujące"},
    {"nazwa": "Zgaga", "refleksy": "przepona, woreczek żółciowy, trzustka, żołądek, wszystkie gruczoły"},
    {"nazwa": "Zapalenie krtani", "refleksy": "gardło, wszystkie palce, układ limfatyczny, klatka piersiowa/płuca"},
    {"nazwa": "Zatoki", "refleksy": "jelito cienkie, wszystkie palce, nadnercza, klatka piersiowa/płuca"},
    {"nazwa": "Zatoki (zapalenie)", "refleksy": "wszystkie palce, jelito cienkie, nadnercza, klatka piersiowa/płuca"},
    {"nazwa": "Zęby (ból)", "refleksy": "wszystkie palce, środek 1/3 dużego palca"},
    {"nazwa": "Żółtaczka", "refleksy": "wątroba"},
    {"nazwa": "Żyły (zapalenie)", "refleksy": "nadnercza, okrężnica, wątroba, równoległe miejsca na ręce"},
    {"nazwa": "Żylaki", "refleksy": "okrężnica, wątroba, nadnercza, równoległe miejsca na rękach"}
  ],
  "mapy": [
    {"refleks": "Głowa, zatoki, mózg", "stopa": "obie", "lokalizacja": "opuszki wszystkich palców"},
    {"refleks": "Przysadka mózgowa", "stopa": "obie", "lokalizacja": "środek opuszka dużego palca"},
    {"refleks": "Kark, kręgi szyjne, tarczyca", "stopa": "obie", "lokalizacja": "podstawa dużego palca"},
    {"refleks": "Oczy / uszy", "stopa": "obie", "lokalizacja": "podstawa palców 2-5"},
    {"refleks": "Płuca / klatka piersiowa", "stopa": "obie", "lokalizacja": "pod palcami, nad linią przepony"},
    {"refleks": "Serce", "stopa": "tylko lewa", "lokalizacja": "pod palcami, w poprzek śródstopia"},
    {"refleks": "Przepona / splot słoneczny", "stopa": "obie", "lokalizacja": "linia przepony"},
    {"refleks": "Wątroba, woreczek żółciowy", "stopa": "tylko prawa", "lokalizacja": "między przeponą a linią pasa"},
    {"refleks": "Żołądek", "stopa": "głównie lewa (~85%)", "lokalizacja": "między przeponą a linią pasa"},
    {"refleks": "Śledziona", "stopa": "tylko lewa", "lokalizacja": "zewnętrzna strona, przy linii pasa"},
    {"refleks": "Nadnercze, nerka, trzustka", "stopa": "obie", "lokalizacja": "przy linii pasa, środek stopy"},
    {"refleks": "Zastawka krętniczo-kątnicza + wyrostek", "stopa": "tylko prawa", "lokalizacja": "dolne, zewnętrzna krawędź, między 4. a 5. strefą"},
    {"refleks": "Esica (zgięcie esowate)", "stopa": "tylko lewa", "lokalizacja": "dolny zewnętrzny róg, najtrudniejsze miejsce"},
    {"refleks": "Pęcherz, przewód moczowy", "stopa": "obie", "lokalizacja": "wewnętrzna krawędź, linia pięty"},
    {"refleks": "Kręgosłup (cały)", "stopa": "obie", "lokalizacja": "wewnętrzna krawędź, od palca do pięty"},
    {"refleks": "Macica / prostata", "stopa": "obie", "lokalizacja": "wewnętrzna kostka, pół linii kostka↔pięta"},
    {"refleks": "Jajnik / jądro", "stopa": "obie", "lokalizacja": "zewnętrzna kostka, pół linii kostka↔pięta"},
    {"refleks": "Chroniczne (prostata/macica/odbytnica/n. kulszowy)", "stopa": "obie", "lokalizacja": "ścięgno Achillesa, ~2 cm nad kostką"},
    {"refleks": "Nerw kulszowy", "stopa": "obie", "lokalizacja": "pasmo w poprzek pięty + zewnętrzna strona"},
    {"refleks": "Kolano / biodro / noga", "stopa": "obie", "lokalizacja": "przed kostką zewnętrzną, góra stopy"},
    {"refleks": "Piersi, ramiona, mięśnie pleców", "stopa": "obie", "lokalizacja": "wierzch stopy, między kośćmi śródstopia"},
    {"refleks": "Zatoki (dłoń)", "stopa": "dłonie", "lokalizacja": "opuszki wszystkich palców dłoni"},
    {"refleks": "Kark, gardło, bark (przestrzeń V)", "stopa": "dłonie", "lokalizacja": "między kciukiem a palcem wskazującym"}
  ],
  "slownik": [
    {"termin": "Refleksologia", "definicja": "Nauka o refleksach w stopach, dłoniach i uszach odpowiadających narządom i częściom ciała; metoda chodzenia kciuka i palców po tych refleksach. Wyrównuje krążenie i pomaga ciału osiągnąć homeostazę. Nie jest masażem ani medycyną."},
    {"termin": "Refleks", "definicja": "Punkt lub mały obszar na stopie/dłoni odpowiadający konkretnemu narządowi, gruczołowi lub części ciała."},
    {"termin": "Homeostaza", "definicja": "Naturalna równowaga (balans) między systemami organizmu; stan, do którego refleksologia pomaga ciału powrócić. Cel każdego zabiegu."},
    {"termin": "Strefa (rejon)", "definicja": "Jeden z 10 podłużnych pasów dzielących ciało (po 5 na każdą połowę), biegnących od palców rąk/stóp do głowy."},
    {"termin": "Miejsce odpowiadające", "definicja": "Refleks na kończynie z tej samej strefy, używany gdy nie można pracować na zranionym miejscu (np. ręka zamiast nogi, łokieć zamiast kolana, przegub zamiast kostki)."},
    {"termin": "Linia przepony (splotu słonecznego)", "definicja": "Pozioma linia pod poduszką stopy, oddziela refleksy klatki piersiowej (powyżej) od jamy brzusznej (poniżej)."},
    {"termin": "Linia pasa (talii)", "definicja": "Pozioma linia w środku stopy, wyznaczana od piątej kości śródstopia; oddziela górną część brzucha od dolnej."},
    {"termin": "Linia pięty", "definicja": "Pozioma linia u nasady pięty, na zakończeniu miękkiego podbicia stopy; oddziela refleksy miednicy."},
    {"termin": "Splot słoneczny", "definicja": "„Mózg jamy brzusznej”, skupisko nerwów za żołądkiem; refleks na linii przepony między 1. a 2. palcem — główny punkt relaksu układu nerwowego."},
    {"termin": "Technika kciuka (gąsienicowanie)", "definicja": "Podstawowa technika: kciuk „idzie” drobnymi krokami tylko do przodu, zginając się w pierwszym stawie, pracując zewnętrznym narożnikiem."},
    {"termin": "Technika zaczepno-wycofująca", "definicja": "Nacisk i lekkie wycofanie (jak żądło pszczoły); dla punktów głębokich i małych: przysadka, esica, zastawka krętniczo-kątnicza."},
    {"termin": "Rotacja refleksu", "definicja": "Okrężne oddziaływanie z podtrzymaniem drugą ręką, na przemian w obu kierunkach; dla miejsc delikatnych i bolących."},
    {"termin": "Zastawka krętniczo-kątnicza", "definicja": "Zastawka między jelitem cienkim a grubym; refleks tylko na prawej stopie (zewnętrzna krawędź, między 4. a 5. strefą), ważny też dla wyrostka robaczkowego."},
    {"termin": "Esica (zgięcie esowate)", "definicja": "Końcowy odcinek okrężnicy; refleks tylko na lewej stopie — najtrudniejsze miejsce; to samo miejsce to refleks pęcherza moczowego."},
    {"termin": "Rejon chroniczny", "definicja": "Okolica ścięgna Achillesa (~2 cm nad kostką) wspólna dla refleksów prostaty, macicy, odbytnicy i nerwu kulszowego — przy stanach przewlekłych."},
    {"termin": "Wszystkie gruczoły", "definicja": "W indeksie schorzeń skrót na: przysadka, tarczyca, przytarczyczki, nadnercza, trzustka, narządy rozrodcze."},
    {"termin": "Kryształki", "definicja": "Wyczuwalne pod kciukiem „ziarenka soli” odłożone w niektórych partiach stóp (np. rejon karku i ramion)."},
    {"termin": "Metoda Budzanowskiej-Bratko", "definicja": "Polska adaptacja metody Ingham; student wykonuje pełny zabieg codziennie (inaczej niż program D.C. Byersa — jeden zabieg na dwa dni)."},
    {"termin": "Eunice Ingham (Ciotka Eunike)", "definicja": "1889-1974, twórczyni nowoczesnej refleksologii stref stóp; autorka „Stories the Feet Can Tell” (1938)."}
  ],
  "testy": [
    {"q": "Ile podłużnych stref dzieli ciało wg teorii strefowej?", "opcje": ["5", "10", "12", "26"], "poprawna": 1, "rozdzial": "r2", "wyj": "Ciało dzieli się na 10 podłużnych stref (po 5 na każdą połowę)."},
    {"q": "Której połowie ciała odpowiada prawa stopa?", "opcje": ["Lewej", "Prawej", "Obu", "Górnej"], "poprawna": 1, "rozdzial": "r2", "wyj": "Prawa stopa = prawa połowa ciała, lewa stopa = lewa połowa."},
    {"q": "Kto jest twórcą terapii strefowej (zone therapy)?", "opcje": ["Eunice Ingham", "William Fitzgerald", "Joe Shelby Riley", "Wanda Bratko"], "poprawna": 1, "rozdzial": "r1", "wyj": "Dr William H. Fitzgerald stworzył terapię strefową."},
    {"q": "W którym roku Eunice Ingham wydała „Historie, które stopy mogą opowiedzieć”?", "opcje": ["1917", "1928", "1938", "1974"], "poprawna": 2, "rozdzial": "r1", "wyj": "Książka ukazała się w 1938 r."},
    {"q": "Gdzie znajduje się refleks przysadki mózgowej?", "opcje": ["Na pięcie", "W środku opuszka dużego palca", "Na małym palcu", "Pod kostką"], "poprawna": 1, "rozdzial": "r12", "wyj": "Refleks przysadki jest w środku powierzchni dużego palca."},
    {"q": "Na której stopie znajduje się refleks serca?", "opcje": ["Tylko prawej", "Tylko lewej", "Obu jednakowo", "Żadnej"], "poprawna": 1, "rozdzial": "r6", "wyj": "Główny refleks serca jest na lewej stopie, w poprzek śródstopia."},
    {"q": "Na której stopie jest refleks zastawki krętniczo-kątniczej?", "opcje": ["Lewej", "Prawej", "Obu", "Na wierzchu obu"], "poprawna": 1, "rozdzial": "r10", "wyj": "Refleks jest na zewnętrznej krawędzi spodu PRAWEJ stopy."},
    {"q": "Na której stopie znajduje się refleks esicy (okrężnicy esowatej)?", "opcje": ["Prawej", "Lewej", "Obu", "Na pięcie prawej"], "poprawna": 1, "rozdzial": "r10", "wyj": "Esica jest tylko na lewej stopie — to samo miejsce co refleks pęcherza."},
    {"q": "Ile kości ma jedna stopa?", "opcje": ["19", "26", "31", "107"], "poprawna": 1, "rozdzial": "r5", "wyj": "Każda stopa ma 26 kości, 107 wiązadeł i 19 mięśni."},
    {"q": "Ile grup kręgów ma kręgosłup?", "opcje": ["3", "4", "5", "7"], "poprawna": 2, "rozdzial": "r5", "wyj": "Pięć grup: szyjne 7, piersiowe 12, lędźwiowe 5, krzyżowa + ogonowa."},
    {"q": "Ile par nerwów wychodzi z kręgosłupa?", "opcje": ["12", "26", "31", "5"], "poprawna": 2, "rozdzial": "r5", "wyj": "Z kręgosłupa wychodzi 31 par nerwów."},
    {"q": "Która półkula mózgu kontroluje prawą stronę ciała?", "opcje": ["Prawa", "Lewa", "Obie", "Żadna"], "poprawna": 1, "rozdzial": "r5", "wyj": "Lewa półkula kontroluje prawą stronę ciała i odwrotnie."},
    {"q": "W którym kierunku zawsze „chodzi” kciuk podczas pracy?", "opcje": ["Do tyłu", "Na boki", "Tylko do przodu", "Po okręgu"], "poprawna": 2, "rozdzial": "r4", "wyj": "Kciuk i palec chodzą zawsze tylko do przodu, nigdy do tyłu ani na bok."},
    {"q": "Pod jakim kątem zgina się kciuk podczas podstawowej techniki?", "opcje": ["~15°", "~45°", "~90°", "Prosto"], "poprawna": 1, "rozdzial": "r4", "wyj": "Kciuk zgina się w pierwszym stawie pod kątem ok. 45°."},
    {"q": "Co oznacza homeostaza?", "opcje": ["Chorobę", "Stan równowagi organizmu", "Rodzaj masażu", "Refleks na pięcie"], "poprawna": 1, "rozdzial": "r2", "wyj": "Homeostaza to stan równowagi (balansu) pracy organizmu."},
    {"q": "Ile płatów ma prawe płuco?", "opcje": ["2", "3", "4", "5"], "poprawna": 1, "rozdzial": "r9", "wyj": "Prawe płuco ma 3 płaty, lewe ma 2."},
    {"q": "Gdzie znajdują się refleksy zatok?", "opcje": ["Na pięcie", "We wszystkich palcach stopy", "Na kostce", "Pod stopą przy linii pasa"], "poprawna": 1, "rozdzial": "r9", "wyj": "Refleksy zatok są we wszystkich palcach stopy."},
    {"q": "Który gruczoł nazywany jest „dyrygentem” / gruczołem głównym?", "opcje": ["Tarczyca", "Nadnercze", "Przysadka mózgowa", "Trzustka"], "poprawna": 2, "rozdzial": "r12", "wyj": "Przysadka mózgowa to gruczoł główny kontrolujący pozostałe."},
    {"q": "Co produkuje rdzeń nadnerczy?", "opcje": ["Insulinę", "Adrenalinę", "Estrogen", "Żółć"], "poprawna": 1, "rozdzial": "r12", "wyj": "Rdzeń nadnerczy wytwarza adrenalinę (reakcja walcz/uciekaj)."},
    {"q": "Który narząd produkuje insulinę?", "opcje": ["Wątroba", "Trzustka", "Śledziona", "Nerki"], "poprawna": 1, "rozdzial": "r12", "wyj": "Insulina powstaje w trzustce (wysepki Langerhansa)."},
    {"q": "Czego NIGDY nie wolno sugerować bez kontaktu z lekarzem?", "opcje": ["Picia wody", "Zmniejszenia dawki insuliny", "Spaceru", "Relaksu"], "poprawna": 1, "rozdzial": "r12", "wyj": "Nigdy nie sugerować zmniejszenia dawki insuliny bez lekarza rodzinnego."},
    {"q": "Na której stopie jest większość refleksów wątroby?", "opcje": ["Lewej", "Prawej", "Obu", "Na wierzchu lewej"], "poprawna": 1, "rozdzial": "r10", "wyj": "Wątroba leży po prawej stronie ciała — refleksy na prawej stopie."},
    {"q": "Ile czynności wykonuje wątroba wg książki?", "opcje": ["Ponad 50", "Ponad 100", "Ponad 500", "Ponad 1000"], "poprawna": 2, "rozdzial": "r10", "wyj": "Wątroba wykonuje ponad 500 czynności."},
    {"q": "Co jest największym skupiskiem tkanki limfatycznej?", "opcje": ["Grasica", "Śledziona", "Migdały", "Węzły pachwinowe"], "poprawna": 1, "rozdzial": "r7", "wyj": "Śledziona to największe skupisko tkanki limfatycznej; magazynuje żelazo."},
    {"q": "Gdzie leży miejsce odpowiadające pachwinie na stopie?", "opcje": ["Na pięcie", "Połączenie stopy z nogą (kostka)", "Na dużym palcu", "Pod małym palcem"], "poprawna": 1, "rozdzial": "r7", "wyj": "Pachwina ma odpowiednik w połączeniu stopy z nogą w kostce."},
    {"q": "Gdzie znajdują się refleksy oczu i uszu?", "opcje": ["Na dużym palcu", "U podstawy małych palców", "Na pięcie", "Na kostce"], "poprawna": 1, "rozdzial": "r8", "wyj": "Refleksy oczu i uszu są u podstawy małych palców obu stóp."},
    {"q": "Jakie miejsce jest pomocnicze dla refleksów oczu?", "opcje": ["Wątroba", "Nerki", "Serce", "Trzustka"], "poprawna": 1, "rozdzial": "r8", "wyj": "Miejsce pomocnicze dla oczu to refleksy nerek (3. strefa)."},
    {"q": "Ile kosteczek wzmacnia dźwięk w uchu?", "opcje": ["1", "2", "3", "4"], "poprawna": 2, "rozdzial": "r8", "wyj": "Trzy: kowadełko, młoteczek, strzemiączko (~22×)."},
    {"q": "Który układ ciała odpowiada za równowagę?", "opcje": ["Ucho zewnętrzne", "Ucho środkowe", "Ucho wewnętrzne", "Nos"], "poprawna": 1, "rozdzial": "r8", "wyj": "Za równowagę odpowiada ucho środkowe (kanały półkoliste z płynem)."},
    {"q": "Co filtrują nerki w przybliżeniu na minutę?", "opcje": ["0,1 l krwi", "1 l krwi", "5 l krwi", "10 l krwi"], "poprawna": 1, "rozdzial": "r11", "wyj": "Nerki filtrują ~1 litr krwi na minutę (ponad 60 l/h)."},
    {"q": "Gdzie najczęściej tworzą się kamienie nerkowe powodujące najwięcej bólu?", "opcje": ["W pęcherzu", "W przewodach moczowych", "W cewce", "W nerce"], "poprawna": 1, "rozdzial": "r11", "wyj": "Najczęściej w przewodach moczowych — tam najwięcej bólu (kolka)."},
    {"q": "Jak nazywa się nadciśnienie w książce?", "opcje": ["„Głośny wróg”", "„Cichy zabójca”", "„Choroba serca”", "„Skaza”"], "poprawna": 1, "rozdzial": "r11", "wyj": "Nadciśnienie to „cichy zabójca” związany z chorobą nerek."},
    {"q": "Gdzie leży refleks macicy/prostaty?", "opcje": ["Zewnętrzna strona stopy", "Wewnętrzna strona stopy, pół linii kostka↔pięta", "Na pięcie", "Na dużym palcu"], "poprawna": 1, "rozdzial": "r13", "wyj": "Wewnętrzna strona stopy, w połowie linii kostka↔krawędź pięty."},
    {"q": "Które refleksy są wspólne w „rejonie chronicznym” ścięgna Achillesa?", "opcje": ["Serce, płuca, wątroba", "Prostata, macica, odbytnica, nerw kulszowy", "Nerki, pęcherz, cewka", "Oczy, uszy, nos"], "poprawna": 1, "rozdzial": "r13", "wyj": "Rejon chroniczny: prostata, macica, odbytnica, nerw kulszowy."},
    {"q": "Co przejmuje produkcję estrogenu po usunięciu jajników?", "opcje": ["Wątroba", "Nadnercza", "Śledziona", "Trzustka"], "poprawna": 1, "rozdzial": "r13", "wyj": "Funkcję estrogenu przejmują nadnercza."},
    {"q": "Jak długo trwa typowy zabieg refleksologii?", "opcje": ["5-10 min", "30-40 min", "90-120 min", "Cały dzień"], "poprawna": 1, "rozdzial": "r14", "wyj": "Zabieg trwa 30-40 min (pierwszy do 60 min)."},
    {"q": "Co refleksolog odpowiada, gdy pacjent pyta o konkretny bolący narząd?", "opcje": ["Podaje dokładny narząd", "Określa najwyżej rejon ciała", "Stawia diagnozę", "Przepisuje lek"], "poprawna": 1, "rozdzial": "r14", "wyj": "Określać najwyżej rejon (głowa/klatka/brzuch/miednica), nie narząd."},
    {"q": "Czy refleksologia jest masażem?", "opcje": ["Tak, zawsze", "Nie — to praca techniką kciuka w rejonach", "Tak, na pięcie", "Tylko na dłoniach"], "poprawna": 1, "rozdzial": "r10", "wyj": "Refleksologia NIE jest masażem (wyjątki: esica i zastawka — technika zaczepno-wycofująca)."},
    {"q": "Co odpowiada kciuk dłoni w refleksologii rąk?", "opcje": ["Pięcie", "Dużemu palcowi stopy", "Kostce", "Małemu palcowi"], "poprawna": 1, "rozdzial": "r15", "wyj": "Kciuk = odpowiednik dużego palca stopy; przegub = kostka."},
    {"q": "Co zawiera przestrzeń „V” między kciukiem a palcem wskazującym?", "opcje": ["Refleksy nerek", "Refleksy karku, gardła, barku", "Refleksy serca", "Refleksy stóp"], "poprawna": 1, "rozdzial": "r15", "wyj": "Przestrzeń „V” zawiera refleksy karku, gardła i barku."},
    {"q": "Wg książki — jaki procent zachorowań wiąże się ze stresem?", "opcje": ["25%", "50%", "75%", "90%"], "poprawna": 2, "rozdzial": "r2", "wyj": "Wg książki ok. 75% zachorowań spowodowanych jest stresami i napięciami."},
    {"q": "Czy refleksologia może spowodować przedawkowanie/uszkodzenie?", "opcje": ["Tak, łatwo", "Nie — daje co najwyżej nieszkodliwe efekty oczyszczania", "Tak, na sercu", "Tylko u dzieci"], "poprawna": 1, "rozdzial": "r2", "wyj": "Refleksologia nie prowadzi do przedawkowania; efekty uboczne to oczyszczanie."},
    {"q": "Gdzie jest refleks tarczycy?", "opcje": ["Na pięcie", "U podstawy dużego palca", "Na małym palcu", "Pod kostką"], "poprawna": 1, "rozdzial": "r12", "wyj": "Tarczyca → refleks u podstawy dużego palca; zwana „trzecim jajnikiem”."},
    {"q": "Przy hipoglikemii i hiperglikemii zawsze pracujemy na refleksach…", "opcje": ["serca i płuc", "trzustki i wątroby", "nerek i pęcherza", "oczu i uszu"], "poprawna": 1, "rozdzial": "r12", "wyj": "Zawsze na refleksach trzustki i wątroby."}
  ],
  "pytania_egz": [
    {"q": "Omów teorię 10 stref ciała i wyjaśnij zasadę: organ w danej strefie ma swój refleks w tej samej strefie stopy.", "rozdzial": "r2", "wskazowka": "10 podłużnych stref, 5 na połowę, prawa stopa = prawa połowa ciała, duży palec = strefa 1 + głowa."},
    {"q": "Wymień i opisz cztery główne linie pomocnicze na stopie.", "rozdzial": "r2", "wskazowka": "Linia przepony (splotu słonecznego), linia pasa (talii), linia pięty, ścięgno."},
    {"q": "Opisz podstawową technikę pracy kciuka i wyjaśnij, dlaczego odchylamy tylko pierwszy staw.", "rozdzial": "r4", "wskazowka": "Chodzenie tylko do przodu, zewnętrzny narożnik, ~45°; 3 powody odchylania pierwszego stawu."},
    {"q": "Czym różni się technika zaczepno-wycofująca od podstawowej techniki kciuka i kiedy ją stosujemy?", "rozdzial": "r4", "wskazowka": "Nacisk i wycofanie, małe głębokie refleksy: przysadka, esica, zastawka krętniczo-kątnicza."},
    {"q": "Opisz drogę pokarmu przez układ trawienny oraz lokalizację głównych refleksów na stopach.", "rozdzial": "r10", "wskazowka": "Usta→gardło→przełyk→żołądek→jelita→odbyt; żołądek lewa, wątroba prawa, esica lewa, zastawka prawa."},
    {"q": "Wyjaśnij, dlaczego refleksologia nie jest masażem i jakie są dwa wyjątki.", "rozdzial": "r10", "wskazowka": "Praca w rejonach techniką kciuka ze zmiennym kątem; wyjątki: esica i zastawka krętniczo-kątnicza."},
    {"q": "Omów budowę i funkcje gruczołów wewnętrznego wydzielania oraz rolę przysadki jako gruczołu głównego.", "rozdzial": "r12", "wskazowka": "Bezprzewodowe, hormony, „termostaty”; przysadka „dyrygent” kontroluje pozostałe; refleks na dużym palcu."},
    {"q": "Przedstaw zasady bezpieczeństwa i ograniczenia pracy refleksologa (czego nie wolno robić).", "rozdzial": "r14", "wskazowka": "Nie diagnozować, nie przepisywać leków, nie zmieniać insuliny, określać tylko rejon, kierować do lekarza."},
    {"q": "Opisz pełny przebieg zabiegu wg metody Budzanowskiej-Bratko — kolejność i czas trwania.", "rozdzial": "r14", "wskazowka": "Jedna stopa A-Z, druga, powrót; przepona→palce→oko/ucho→pięta→kręgosłup→kostka; 30-40 min."},
    {"q": "Wyjaśnij rolę nadnerczy i adrenaliny oraz znaczenie refleksu nadnercza w pracy refleksologa.", "rozdzial": "r12", "wskazowka": "Rdzeń → adrenalina (walcz/uciekaj); pomoc przy sercu, astmie, stanach zapalnych; refleks między linią pasa a przepony przy ścięgnie."},
    {"q": "Omów układ moczowy i wyjaśnij związek nadciśnienia z pracą nerek.", "rozdzial": "r11", "wskazowka": "Nerki/moczowody/pęcherz/cewka; nadciśnienie „cichy zabójca”; praca: przepona + nerki + gruczoły."},
    {"q": "Opisz lokalizację refleksów układu rozrodczego i znaczenie rejonu chronicznego.", "rozdzial": "r13", "wskazowka": "Macica/prostata wewn. kostka, jajniki/jądra zewn. kostka; rejon chroniczny = ścięgno Achillesa."},
    {"q": "Wyjaśnij, na czym polega zasada miejsc odpowiadających i podaj przykłady.", "rozdzial": "r2", "wskazowka": "Gdy nie można pracować na zranionym miejscu: dłoń↔podeszwa, łokieć↔kolano, kostka↔przegub."},
    {"q": "Przedstaw znaczenie kręgosłupa w refleksologii i dlaczego pracujemy na nim w każdym zabiegu.", "rozdzial": "r5", "wskazowka": "Oś układu nerwowego, 31 par nerwów, refleks na wewn. krawędzi stopy; stały element zabiegu."},
    {"q": "Omów refleksologię rąk — kiedy ją stosujemy i jakie są różnice względem stóp.", "rozdzial": "r15", "wskazowka": "Praca pacjenta + wyjście gdy nie można na stopach; te same strefy; trudniejsze do odnalezienia; kciuk=duży palec."}
  ]
}
;
